#!/bin/sh
## Mail notification when an Adblock host is not reachable by xfuentes
## Variables without description should not be modified
## Required package: mutt

## DEFINE VARIABLES
adblock=/opt/adblock/adblock.sh       ## path of adblock.sh; default: /opt/adblock/adblock.sh
alias logger='logger -t "ADBLOCK" -s' ## name that will be displayed in the logs and terminal; default: "ADBLOCK"
counter=0
directory=/opt/adblock/               ## directory where adblock.sh is saved; default: /opt/adblock/
file=source-*
fromname="Cisco E4200"                ## make and model of the router; default: "Cisco E4200"
log=/opt/logs/syslog/messages         ## path of the log file
maxcount=7                            ## maximum number download retries; defaut: 7
minimumsize=1
to="your@emailhere.com"               ## email address where the notification will be sent


## BEGIN TEST
  logger Starting Adblock source data update.
  [[ -x $adblock ]] && $adblock force

check()
{
  if [ $counter -lt $maxcount ]; then
    killall adblock.sh
    logger Starting Adblock source data integrity check.
    for i in $directory$file
      do
        actualsize=$(wc -c "$i" | cut -f 1 -d ' ')
          if [ $actualsize -ge $minimumsize ]; then
            logger "$i size is ok, redownload not required."
          else
            logger "$i size is zero, redownloading host file."
            [[ -x $adblock ]] && $adblock force
            let counter=counter+1
            check
          fi
      done
      logger Adblock source data updated successfully.
  else
    logger -t "MAIL NOTIFICATION" -s "Mail sent, about Adblock host source error."

    echo "Subject: Adblock source error + logs" >>/opt/adblocksource.txt
    echo "From: $fromname" >>/opt/adblocksource.txt
    echo "Date: `date -R`" >>/opt/adblocksource.txt
    echo "" >>/opt/adblocksource.txt
    echo "" >>/opt/adblocksource.txt
    echo "Source data integrity check completed:" >>/opt/adblocksource.txt
    echo "`date +\%d/\%m/\%Y` at `date +\%T`" >>/opt/adblocksource.txt
    echo "" >>/opt/adblocksource.txt
    echo "" >>/opt/adblocksource.txt
    echo "Your awesome router." >>/opt/adblocksource.txt

    cat /opt/adblocksource.txt | mutt -s "Adblock source error + log" -a $log -- $to
    rm /opt/adblocksource.txt
  fi
  
  logger Adblock source data integrity check completed.
  killall adupdate2
}
check
